### ISSUE TITLE
[ 1.21.1 - Neoforge ] 与 Arclight1.21.1 不兼容

### ISSUE THREAD

**Issue by windy664** [Coloryr/AllMusic_Server#43]
[18:48:52 INFO] [n.n.f.l.m.l.JarInJarDependencyLocator]: Found 38 dependencies adding them to mods collection
java.lang.module.ResolutionException: Module okhttp3 reads more than one module named org.xerial.sqlitejdbc
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:721)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:87)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:90)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at MC-BOOTSTRAP/arclight.boot@1.21.1-1.0.0-SNAPSHOT/io.izzel.arclight.boot.neoforge.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:47)
        at MC-BOOTSTRAP/arclight.boot@1.21.1-1.0.0-SNAPSHOT/io.izzel.arclight.boot.neoforge.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:14)
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.izzel.arclight.boot.neoforge.application.Main_Neoforge.main(Main_Neoforge.java:23)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:39)

**Comment by windy664** [comment]
[19:13:29 INFO] [AllMusic_Server]: [AllMusic3]��ǰ���������ļ��汾Ϊ��205����������ļ��汾Ϊ��205
[19:13:29 INFO] [m.c.Mekanism]: Loaded 'Mekanism: Generators' module.
[19:13:29 WARN] [AllMusic_Server]: [AllMusic3]�����ļ��������
[19:13:29 ERROR] [STDERR]: java.lang.TypeNotPresentException: Type okhttp3.Cookie not present
[19:13:29 ERROR] [STDERR]:      at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
[19:13:29 ERROR] [STDERR]:      at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
[19:13:29 ERROR] [STDERR]:      at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
[19:13:29 ERROR] [STDERR]:      at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
[19:13:29 ERROR] [STDERR]:      at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
[19:13:29 ERROR] [STDERR]:      at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
[19:13:29 ERROR] [STDERR]:      at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
[19:13:29 ERROR] [STDERR]:      at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
[19:13:29 ERROR] [STDERR]:      at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
[19:13:29 ERROR] [STDERR]:      at java.base/sun.reflect.generics.repository.FieldRepository.computeGenericType(FieldRepository.java:90)
[19:13:29 ERROR] [STDERR]:      at java.base/sun.reflect.generics.repository.FieldRepository.getGenericType(FieldRepository.java:82)
[19:13:29 ERROR] [STDERR]:      at java.base/java.lang.reflect.Field.getGenericType(Field.java:294)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:288)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.Gson.getAdapter(Gson.java:556)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.Gson.toJson(Gson.java:834)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.Gson.toJson(Gson.java:812)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.Gson.toJson(Gson.java:759)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/com.google.gson@2.10.1/com.google.gson.Gson.toJson(Gson.java:736)
[19:13:29 ERROR] [STDERR]:      at TRANSFORMER/allmusic_server@3.2.7/com.coloryr.allmusic.server.core.AllMusic.saveCookie(AllMusic.java:281)
[19:13:29 ERROR] [STDERR]:      at TRANSFORMER/allmusic_server@3.2.7/com.coloryr.allmusic.server.core.AllMusic.loadConfig(AllMusic.java:368)
[19:13:29 ERROR] [STDERR]:      at TRANSFORMER/allmusic_server@3.2.7/com.coloryr.allmusic.server.core.AllMusic.init(AllMusic.java:440)
[19:13:29 ERROR] [STDERR]:      at TRANSFORMER/allmusic_server@3.2.7/com.coloryr.allmusic.server.AllMusicForge.commonSetup(AllMusicForge.java:59)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:158)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$dispatchParallelEvent$4(ModLoader.java:172)
[19:13:29 ERROR] [STDERR]:      at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231)
[19:13:29 ERROR] [STDERR]:      at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
[19:13:29 ERROR] [STDERR]:      at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
[19:13:29 ERROR] [STDERR]:      at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:13:29 ERROR] [STDERR]:      at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[19:13:29 ERROR] [STDERR]:      at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[19:13:29 ERROR] [STDERR]:      at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[19:13:29 ERROR] [STDERR]:      at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[19:13:29 ERROR] [STDERR]:      at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[19:13:29 ERROR] [STDERR]: Caused by: java.lang.ClassNotFoundException: okhttp3.Cookie
[19:13:29 ERROR] [STDERR]:      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[19:13:29 ERROR] [STDERR]:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[19:13:29 ERROR] [STDERR]:      at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216)
[19:13:29 ERROR] [STDERR]:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[19:13:29 ERROR] [STDERR]:      at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216)
[19:13:29 ERROR] [STDERR]:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[19:13:29 ERROR] [STDERR]:      at java.base/java.lang.Class.forName0(Native Method)
[19:13:29 ERROR] [STDERR]:      at java.base/java.lang.Class.forName(Class.java:534)
[19:13:29 ERROR] [STDERR]:      at java.base/java.lang.Class.forName(Class.java:513)
[19:13:29 ERROR] [STDERR]:      at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
[19:13:29 ERROR] [STDERR]:      ... 36 more
[19:13:29 INFO] [AllMusic_Server]: [AllMusic3]��ǰ��������ļ��汾Ϊ��203����������ļ��汾Ϊ��203

**Comment by JingHai-Lingyun** [comment]
发日志文件吧……

**Comment by Coloryr** [comment]
安装bukkit插件版
